version: '3'
services:
  mongo:
    image: mongo:latest
    restart: always
    volumes:
      - ./db:/data/db
      - ./mongo:/etc/mongo
    expose:
      - "27017"
    command:
      - '-f'
      - '/etc/mongo/mongod.conf'
  api:
    build: ./api
    restart: always
    links:
      - mongo
    expose:
      - "8080"
  nginx:
    build: ./view
    restart: always
    links:
      - api
    ports:
      - "8080:80"
