version: '3'
services:
  mongo:
    image: mongo:latest
    restart: always
    volumes:
      - ./db:/data/db
      - ./mongo:/etc/mongo
    ports:
      - "27017:27017"
    command:
      - '-f'
      - '/etc/mongo/mongod.conf'
  go_api:
    build: ./api
    image: golang:latest
    working_dir: /go/src/api
    links:
      - mongo
    ports:
      - "8080:8080"
    volumes:
      - ./api:/go/src/api
    command: 'go run main.go'
