version: '3'
services:
  mongo:
    image: mongo:latest
    restart: always
    volumes:
      - ./db:/data/db
      - ./mongo:/etc/mongo
    expose:
      - "27017"
    command:
      - '-f'
      - '/etc/mongo/mongod.conf'
  go_api:
    build: ./api
    image: golang:latest
    restart: always
    links:
      - mongo
    ports:
      - "8080:8080"
    command: './api'
